import type { AnalyzeRequest, AnalyzeResponse } from "@/types";

export function generateReport(req: AnalyzeRequest, res: AnalyzeResponse): string {
  const border = "═".repeat(46);
  const divider = "─".repeat(46);
  const now = new Date().toLocaleString("en-IN", {
    dateStyle: "full",
    timeStyle: "short",
  });

  const lines: string[] = [
    `╔${border}╗`,
    `║${"  MINDSPACE WELLNESS REPORT".padEnd(46)}║`,
    `╚${border}╝`,
    "",
    `Generated : ${now}`,
    `Exam      : ${req.examType}`,
    `Mood      : ${req.moodScore}/5`,
    divider,
    "",
    "EMOTIONAL HEALTH",
    `State      : ${res.health.emotionalState}`,
    `Burnout    : ${res.health.burnoutRisk.toUpperCase()} (${res.health.burnoutScore}/100)`,
    `Emotion    : ${res.health.primaryEmotion}`,
    "",
    "Key Insights:",
    ...res.health.insights.map((i) => `  • ${i}`),
    "",
    `Affirmation: "${res.health.affirmation}"`,
    "",
    divider,
    "STRESS TRIGGERS",
  ];

  if (res.triggers.rankedTriggers.length > 0) {
    res.triggers.rankedTriggers.forEach((t) => {
      lines.push(`  • ${t.trigger} [${t.severity.toUpperCase()}]`);
      if (t.rootCause) lines.push(`    Root: ${t.rootCause}`);
    });
    if (res.triggers.overallMessage) {
      lines.push("", `Pattern: ${res.triggers.overallMessage}`);
    }
  } else {
    lines.push("  No specific triggers identified.");
  }

  lines.push(
    "",
    divider,
    "WELLNESS PLAN",
    "",
    `Immediate — ${res.wellness.immediateAction.title} (${res.wellness.immediateAction.duration})`,
    ...res.wellness.immediateAction.steps.map((s) => `  → ${s}`),
    "",
    `Study Strategy — ${res.wellness.studyStrategy.title}`,
    ...res.wellness.studyStrategy.tips.map((s) => `  → ${s}`),
    "",
    `Self-Care — ${res.wellness.selfCare.title}`,
    ...res.wellness.selfCare.activities.map((s) => `  → ${s}`),
    "",
    `"${res.wellness.motivationalMessage}"`,
    "",
    `Weekly Goal: ${res.wellness.weeklyGoal}`,
    "",
    divider,
    "CRISIS SUPPORT",
    "  iCall (TISS)          : 9152987821",
    "  Vandrevala Foundation : 1860-2662-345",
    "  NIMHANS               : 080-46110007",
    "  Snehi                 : 044-24640050",
    "",
    "Generated by MindSpace · PromptWars 2025",
  );

  return lines.join("\n");
}
